version: '3.8'

services:
  app:
    build: .
    container_name: lumen-app
    ports:
      - "8100:8000"
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_KEY=base64:your-app-key-here
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=lumen_api
      - DB_USERNAME=lumen_user
      - DB_PASSWORD=lumen_password

    volumes:
      - .:/var/www
      - ./storage:/var/www/storage
    depends_on:
      - db
    networks:
      - lumen-network

  db:
    image: mysql:8.0
    container_name: lumen-db
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=lumen_api
      - MYSQL_USER=lumen_user
      - MYSQL_PASSWORD=lumen_password
      - MYSQL_ROOT_PASSWORD=root_password
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/init:/docker-entrypoint-initdb.d
    networks:
      - lumen-network

  nginx:
    image: nginx:alpine
    container_name: lumen-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www
    depends_on:
      - app
    networks:
      - lumen-network

volumes:
  mysql_data:

networks:
  lumen-network:
    driver: bridge
